1. Business Understanding

Insurance Risk Analytics — Hypothesis Testing
Business Objective

The objective of this analysis is to statistically validate whether significant insurance risk differences exist across provinces, postal codes, and gender groups.

The findings will support:

Risk-based pricing
Geographic segmentation
Customer targeting
Portfolio optimization
Marketing strategy decisions

Risk is evaluated using:

Loss Ratio
Margin
Claim behavior

Statistical hypothesis testing enables AlphaCare Insurance Solutions (ACIS) to make evidence-driven pricing decisions rather than relying on intuition.

In [1]:
import pandas as pd
import numpy as np

from scipy.stats import ttest_ind

pd.set_option("display.max_columns", None)

df = pd.read_csv(
    "../data/insurance_data.txt",
    sep="|",
    low_memory=False
)

print(df.shape)

(1000098, 52)

Feature Engineering

This section creates derived insurance risk metrics used throughout the hypothesis testing process.

In [2]:
# loss ratio
df["LossRatio"] = (
    df["TotalClaims"] /
    df["TotalPremium"]
)

# margin
df["Margin"] = (
    df["TotalPremium"] -
    df["TotalClaims"]
)

# remove invalid values
df = df.replace([np.inf, -np.inf], np.nan)

df = df.dropna(
    subset=["LossRatio", "Margin"]
)

df.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,MaritalStatus,Gender,Country,Province,PostalCode,MainCrestaZone,SubCrestaZone,ItemType,mmcode,VehicleType,RegistrationYear,make,Model,Cylinders,cubiccapacity,kilowatts,bodytype,NumberOfDoors,VehicleIntroDate,CustomValueEstimate,AlarmImmobiliser,TrackingDevice,CapitalOutstanding,NewVehicle,WrittenOff,Rebuilt,Converted,CrossBorder,NumberOfVehiclesInFleet,SumInsured,TermFrequency,CalculatedPremiumPerTerm,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims,LossRatio,Margin
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0,0.0,21.929825
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,0.01,Monthly,25.0000,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0,0.0,21.929825
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,119300.00,Monthly,584.6468,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0,0.0,512.848070
5,145247,12827,2015-01-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,500000.00,Monthly,57.5412,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,3.256435,0.0,0.0,3.256435
6,145247,12827,2015-04-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,Not specified,Not specified,South Africa,Gauteng,1459,Rand East,Rand East,Mobility - Motor,44069150.0,Passenger Vehicle,2004,MERCEDES-BENZ,E 240,6.0,2597.0,130.0,S/D,4.0,6/2002,119300.0,Yes,No,119300,More than 6 months,NaN,NaN,NaN,NaN,NaN,500000.00,Monthly,57.5412,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,50.474737,0.0,0.0,50.474737

In [17]:
import sys
import os

sys.path.append(
    os.path.abspath("../src")
)

from hypothesis_tests import run_ttest

province_p = p_value

In [4]:
print(run_ttest)

<function run_ttest at 0x0000022471357C40>

Hypothesis 1: Province Risk Difference
Null Hypothesis (H₀)

There is no significant difference in insurance risk between Gauteng and Western Cape.

Alternative Hypothesis (H₁)

There is a significant difference in insurance risk between Gauteng and Western Cape.

KPI Used:

Loss Ratio

In [20]:
gauteng = df[
    df["Province"] == "Gauteng"
]["LossRatio"]

western_cape = df[
    df["Province"] == "Western Cape"
]["LossRatio"]

stat, p_value = run_ttest(
    gauteng,
    western_cape
)

print("P-value:", p_value)

province_p = p_value

P-value: 0.058900756521706316

Decision Rule:
Reject H₀ if p < 0.05.

Interpretation:
(you will fill after seeing result)

In [19]:
df["PostalCode"].value_counts().head(10)

PostalCode
2000    90944
122     27898
299     16731
7784    13563
7405    10731
8000     8855
458      8392
2196     7277
470      7052
4360     6555
Name: count, dtype: int64

Hypothesis 2: Zip Code Risk Difference
H₀

There is no significant risk difference between selected postal codes.

KPI

Loss Ratio

In [21]:
zip1 = df[
    df["PostalCode"] == 2000
]["LossRatio"]

zip2 = df[
    df["PostalCode"] == 8001
]["LossRatio"]

stat, p_value = run_ttest(
    zip1,
    zip2
)

print("P-value:", p_value)

zip_p = p_value

P-value: 0.6646162787482979

Hypothesis 3: Margin Difference by Postal Code
H₀

There is no significant margin difference between selected postal codes.

In [22]:
margin_zip1 = df[
    df["PostalCode"] == 2000
]["Margin"]

margin_zip2 = df[
    df["PostalCode"] == 8001
]["Margin"]

stat, p_value = run_ttest(
    margin_zip1,
    margin_zip2
)

print("P-value:", p_value)

margin_p = p_value

P-value: 0.9534883109366369

Hypothesis 4: Gender Risk Difference
H₀

There is no significant insurance risk difference between women and men.

KPI

Loss Ratio

In [24]:
male = df[
    df["Gender"] == "Male"
]["LossRatio"]

female = df[
    df["Gender"] == "Female"
]["LossRatio"]

stat, p_value = run_ttest(
    male,
    female
)

print("P-value:", p_value)

gender_p = p_value

P-value: 0.549506376964734

Results Summary

In [25]:
results = pd.DataFrame({
    "Hypothesis": [
        "Province Risk Difference",
        "Zip Code Risk Difference",
        "Margin Difference",
        "Gender Risk Difference"
    ],
    "Test": [
        "T-Test",
        "T-Test",
        "T-Test",
        "T-Test"
    ],
    "P-Value": [
        province_p,
        zip_p,
        margin_p,
        gender_p
    ]
})

results["Decision"] = np.where(
    results["P-Value"] < 0.05,
    "Reject H0",
    "Fail to Reject H0"
)

results

                 Hypothesis    Test   P-Value           Decision
0  Province Risk Difference  T-Test  0.549506  Fail to Reject H0
1  Zip Code Risk Difference  T-Test  0.664616  Fail to Reject H0
2         Margin Difference  T-Test  0.953488  Fail to Reject H0
3    Gender Risk Difference  T-Test  0.549506  Fail to Reject H0

Business Recommendations
Geographic Pricing

If provincial risk differences are statistically significant, ACIS should consider province-adjusted pricing strategies.

Postal Code Segmentation

Significant postal code differences may indicate localized risk clusters requiring more granular pricing models.

Gender-Based Insights

If gender differences are statistically significant, further investigation into behavioral and exposure factors may improve segmentation strategies.

Profitability Optimization

Margin differences across postal codes suggest opportunities for targeted portfolio optimization and marketing investment allocation.